plugins:
  - './node_modules/@trivago/prettier-plugin-sort-imports' # import 排序插件
importOrder: # import 排序顺序，按需添加
  - '<THIRD_PARTY_MODULES>' # node_modules
  - '^@/common/apis/(.*)$'
  - '^@/common/interfaces/(.*)$'
  - '^@/common/consts/(.*)$'
  - '^@/layout/(.*)$'
  - '^@/pages/(.*)$'
  - '^@/models/(.*)$'
  - '^@/components/(.*)$'
  - '^[../]'
  - '^[./]'
importOrderSeparation: true # import 排序
importOrderSortSpecifiers: true # import {x, y, z}排序
singleQuote: true # 单引号
semi: false # 不要语句结束分号
